<?php

namespace App\Http\Controllers\Auth;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Str;
use Illuminate\Validation\Rule;
use Illuminate\View\View;

class RegisteredUserController extends Controller
{
    public function create(): View
    {
        return view('auth.register');
    }

    public function store(Request $request): RedirectResponse
    {
        $validated = $request->validate([
            'account_type' => ['required', Rule::in(['student', 'lecturer'])],
            'first_name' => ['required', 'string', 'max:100'],
            'last_name' => ['required', 'string', 'max:100'],
            'gender' => ['required', Rule::in(['Male', 'Female'])],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users,email'],
            'password' => ['required', 'confirmed', 'min:8'],
            'faculty' => ['required', Rule::in(['SCES', 'SIMS', 'SLS', 'SBS', 'STH', 'SHSS', 'SI'])],
            'course' => ['nullable', 'string', 'max:120', 'required_if:account_type,student'],
            'admission_number' => ['nullable', 'string', 'required_if:account_type,student', 'regex:/^\d{6}$/', 'unique:users,admission_number'],
            'year_of_study' => ['nullable', Rule::in(['1', '2', '3', '4', '5']), 'required_if:account_type,student'],
            'employee_id' => ['nullable', 'string', 'required_if:account_type,lecturer', 'regex:/^\d{5,6}$/', 'unique:users,employee_id'],
            'office_location' => ['nullable', 'string', 'max:150', 'required_if:account_type,lecturer'],
            'registration_token' => ['required', 'string', 'size:6'],
        ], [
            'required' => 'This field is required.',
            'required_if' => 'This field is required.',
            'email.unique' => 'An account with this email address already exists.',
            'admission_number.unique' => 'An account with this admission number already exists.',
            'employee_id.unique' => 'An account with this employee ID already exists.',
            'admission_number.regex' => 'Admission number must be exactly 6 digits.',
            'employee_id.regex' => 'Employee ID must be 5 or 6 digits.',
            'password.confirmed' => 'Passwords do not match.',
            'registration_token.size' => 'Token must be 6 digits.',
        ]);

        $sourceIdentifier = $validated['account_type'] === 'lecturer'
            ? ($validated['employee_id'] ?? '')
            : ($validated['admission_number'] ?? '');

        $generatedUsername = (string) Str::of((string) $sourceIdentifier)
            ->replaceMatches('/\s+/', '')
            ->lower();

        if ($generatedUsername === '') {
            return back()
                ->withErrors(['username' => 'Username could not be generated. Check your Admission Number or Employee ID.'])
                ->withInput();
        }

        if (User::query()->where('username', '=', $generatedUsername)->exists()) {
            return back()
                ->withErrors(['username' => 'An account already exists for this Admission Number or Employee ID.'])
                ->withInput();
        }

        // Verify the email token that was previously generated by sendToken().
        $cacheKey = $this->registrationTokenCacheKey($validated['email']);
        $cachedTokenPayload = Cache::get($cacheKey);

        if (! is_array($cachedTokenPayload) || ! isset($cachedTokenPayload['token'], $cachedTokenPayload['identifier'])) {
            return back()
                ->withErrors(['registration_token' => 'Token is missing or expired. Please click Send Token again.'])
                ->withInput();
        }

        // Prevent token reuse with altered identity details (admission/employee changes).
        if (($cachedTokenPayload['identifier'] ?? null) !== $generatedUsername) {
            return back()
                ->withErrors(['registration_token' => 'Your details changed after token generation. Please click Send Token again.'])
                ->withInput();
        }

        // Constant-time token comparison helps avoid timing-based leaks.
        if (! hash_equals((string) $cachedTokenPayload['token'], (string) $validated['registration_token'])) {
            return back()
                ->withErrors(['registration_token' => 'Invalid token. Please check your email and try again.'])
                ->withInput();
        }

        $roleId = $validated['account_type'] === 'lecturer' ? 3 : 2;

        $user = User::create([
            'name' => trim($validated['first_name'].' '.$validated['last_name']),
            'email' => $validated['email'],
            'password' => $validated['password'],
            'active' => true,
            'role_id' => $roleId,
            'first_name' => $validated['first_name'],
            'last_name' => $validated['last_name'],
            'gender' => $validated['gender'],
            'account_type' => $validated['account_type'],
            'admission_number' => $validated['account_type'] === 'student' ? $validated['admission_number'] : null,
            'employee_id' => $validated['account_type'] === 'lecturer' ? $validated['employee_id'] : null,
            'faculty' => $validated['faculty'],
            'year_of_study' => $validated['account_type'] === 'student' ? $validated['year_of_study'] : null,
            'office_location' => $validated['account_type'] === 'lecturer' ? $validated['office_location'] : null,
            'username' => $generatedUsername,
            'course' => $validated['course'] ?? null,
        ]);

        // Invalidate token after successful registration so it cannot be replayed.
        Cache::forget($cacheKey);

        Auth::login($user);

        return redirect()->route('bookings.index')->with('success', 'Registration successful. Welcome to SU-Spaces.');
    }

    public function sendToken(Request $request): JsonResponse
    {
        // Validate all registration fields before sending a verification token.
        $validated = $request->validate([
            'account_type' => ['required', Rule::in(['student', 'lecturer'])],
            'first_name' => ['required', 'string', 'max:100'],
            'last_name' => ['required', 'string', 'max:100'],
            'gender' => ['required', Rule::in(['Male', 'Female'])],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users,email'],
            'password' => ['required', 'confirmed', 'min:8'],
            'faculty' => ['required', Rule::in(['SCES', 'SIMS', 'SLS', 'SBS', 'STH', 'SHSS', 'SI'])],
            'course' => ['nullable', 'string', 'max:120', 'required_if:account_type,student'],
            'admission_number' => ['nullable', 'string', 'required_if:account_type,student', 'regex:/^\d{6}$/', 'unique:users,admission_number'],
            'year_of_study' => ['nullable', Rule::in(['1', '2', '3', '4', '5']), 'required_if:account_type,student'],
            'employee_id' => ['nullable', 'string', 'required_if:account_type,lecturer', 'regex:/^\d{5,6}$/', 'unique:users,employee_id'],
            'office_location' => ['nullable', 'string', 'max:150', 'required_if:account_type,lecturer'],
        ], [
            'required' => 'This field is required.',
            'required_if' => 'This field is required.',
            'email.unique' => 'An account with this email address already exists.',
            'admission_number.unique' => 'An account with this admission number already exists.',
            'employee_id.unique' => 'An account with this employee ID already exists.',
            'admission_number.regex' => 'Admission number must be exactly 6 digits.',
            'employee_id.regex' => 'Employee ID must be 5 or 6 digits.',
            'password.confirmed' => 'Passwords do not match.',
        ]);

        $sourceIdentifier = $validated['account_type'] === 'lecturer'
            ? ($validated['employee_id'] ?? '')
            : ($validated['admission_number'] ?? '');

        $generatedUsername = (string) Str::of((string) $sourceIdentifier)
            ->replaceMatches('/\s+/', '')
            ->lower();

        if ($generatedUsername === '') {
            return response()->json([
                'message' => 'Username could not be generated. Check your Admission Number or Employee ID.',
            ], 422);
        }

        if (User::query()->where('username', '=', $generatedUsername)->exists()) {
            return response()->json([
                'message' => 'An account already exists for this Admission Number or Employee ID.',
            ], 422);
        }

        // Generate a 6-digit email verification token.
        $token = (string) random_int(100000, 999999);

        // Store token against email for 15 minutes; also bind to generated identifier.
        Cache::put(
            $this->registrationTokenCacheKey($validated['email']),
            [
                'token' => $token,
                'identifier' => $generatedUsername,
            ],
            now()->addMinutes(15)
        );

        // Send email asynchronously after response for better perceived speed.
        dispatch(function () use ($validated, $token): void {
            Mail::raw(
                "Your SU-Spaces registration token is: {$token}. This token expires in 15 minutes.",
                function ($message) use ($validated): void {
                    $message->to($validated['email'])
                        ->subject('SU-Spaces Registration Token');
                }
            );
        })->afterResponse();

        return response()->json([
            'message' => 'Token sent successfully. Check your email and paste it below.',
        ]);
    }

    private function registrationTokenCacheKey(string $email): string
    {
        return 'registration_token:'.Str::lower(trim($email));
    }
}